name: Build and Deploy

on:
  push:
    paths:
      - 'ulc/src/**'
  pull_request:
    paths:
      - 'ulc/src/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd ulc/src
          npm install

      - name: Build project
        run: |
          cd ulc/src
          npm run build

      - name: Copy build output
        run: |
          mkdir -p html
          cp -r ulc/src/dist/* html/

      - name: Commit build output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd html
          git init
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Deploy build output"
          git branch -M main
          git remote add origin https://github.com/${{ github.repository }}.git
          git push --force origin main
